# -*- coding: utf-8 -*-
"""Managing Hierarchical Indexing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ss7yA6yPti6Qhi56kfBIH01G9dccwdPH

**Titanic Dataset Exploration Modeling**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/Titanic-Dataset.csv')
df.head()

passGNDR = df.groupby('Sex')['Embarked'].count().reset_index()
passGNDR.columns = ['Sex', 'Number of Voyagers']

sns.barplot(x='Sex',y='Number of Voyagers',data=passGNDR)
plt.title('Voyagers by Gender')
plt.show()
sns.set_theme(rc={'figure.figsize':(7,7)})

sexCL = df['Sex'].value_counts()
sexCL

plt.figure(figsize=(5,10))

plt.pie(sexCL, labels=['Male', 'Female'], autopct='%1.1f%%', colors=['pink','green'])
plt.title('Males vs. Females (TOTAL)')

plt.legend()
plt.show()

voyagerGNDR=df[['Embarked','Sex']].value_counts().reset_index()
voyagerGNDR

plt.figure(figsize=(10,10))
sns.barplot(data=voyagerGNDR , x=voyagerGNDR['Embarked'], y=voyagerGNDR['count'], hue=voyagerGNDR['Sex'])
plt.title('Voyagers and Gender')
plt.xlabel('Embarked')
plt.ylabel('Count')
plt.show()

peopleBOARD = df['Embarked'].value_counts()
peopleBOARD

plt.figure(figsize=(5,10))

plt.pie(peopleBOARD, labels=['S', 'C', 'Q'], autopct='%1.1f%%', colors=['pink','cyan', 'yellow'])
plt.title('boarding location percentage')

plt.legend()
plt.show()

classPN = df['Pclass'].value_counts()
classPN

plt.figure(figsize=(5,10))

plt.pie(classPN, labels=['1', '2', '3'], autopct='%1.1f%%', colors=['pink','cyan', 'yellow'])
plt.title('total people in classes')

plt.legend()
plt.show()

pclGNDR=df.groupby(['Pclass', 'Sex']).size().reset_index(name='Count')


sns.barplot(x='Pclass', y='Count', hue='Sex', data=pclGNDR)
plt.title('Class Distribution by Sex')
plt.xlabel('Passenger Class')
plt.ylabel('Number of Passengers')
plt.show()

survivalsGNDR = df.groupby('Sex')['Survived'].sum().reset_index()
survivalsGNDR.columns = ['Sex', 'Number of Survivors']

sns.barplot(x='Sex', y='Number of Survivors',data=survivalsGNDR)
plt.title('Survivors by Sex')

survivalsAGE = df.groupby('Age')['Survived'].sum().reset_index()
survivalsAGE.columns = ['Age', 'Number of Survivors']

sns.barplot(x='Age', y='Number of Survivors',data=survivalsAGE)
plt.title('Survivors by Age')
sns.set_theme(rc={'figure.figsize':(70, 70)})

survivalsCL = df.groupby('Pclass')['Survived'].sum().reset_index()
survivalsCL.columns = ['Class', 'Number of Survivors']

sns.barplot(x='Class', y='Number of Survivors',data=survivalsCL)
plt.title('Survivors by Class')
sns.set_theme(rc={'figure.figsize':(7,7)})

survivalsBOARD = df.groupby('Embarked')['Survived'].sum().reset_index()
survivalsBOARD.columns = ['Embarked', 'Number of Survivors']

sns.barplot(x='Embarked', y='Number of Survivors',data=survivalsBOARD)
plt.title('Survivors by Embarking place')

sns.set_theme(rc={'figure.figsize':(7,7)})

df['FamilySize'] = df['SibSp'] + df['Parch']
survivalFAM = df.groupby('FamilySize')['Survived'].mean().reset_index()

plt.figure(figsize=(10, 6))
plt.bar(survivalFAM['FamilySize'], survivalFAM['Survived'], color='skyblue')
plt.title('Survival Rate by Family Size')
plt.xlabel('Family Size')
plt.ylabel('Average Survival Rate')
plt.xticks(survivalFAM['FamilySize'])
plt.grid(axis='y')
plt.show()

